"use client"

import { useState } from "react"
import { Send, Copy, Share, Zap } from "lucide-react"

import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Textarea } from "@/components/ui/textarea"
import { useToast } from "@/hooks/use-toast"

export default function IssueStitcher() {
  const [issueDescription, setIssueDescription] = useState("")
  const [analysis, setAnalysis] = useState("")
  const [loading, setLoading] = useState(false)
  const { toast } = useToast()

  const submitIssue = async () => {
    if (!issueDescription.trim()) return

    setLoading(true)
    try {
      await new Promise((resolve) => setTimeout(resolve, 2000))

      const mockAnalysis = `# Elasticsearch Issue Analysis

## Problem Summary
Based on your description, you're experiencing performance degradation in your Elasticsearch cluster. Here's my analysis:

## Root Cause Analysis
1. **High Query Latency**: The symptoms suggest index fragmentation or suboptimal query patterns
2. **Memory Pressure**: JVM heap usage patterns indicate potential memory leaks
3. **Shard Imbalance**: Uneven shard distribution across nodes

## Recommended Solutions

### Immediate Actions
- **Optimize Queries**: Review and optimize frequently used queries
- **Index Maintenance**: Run \`_forcemerge\` on indices with high segment count
- **Memory Tuning**: Adjust JVM heap settings based on node capacity

### Long-term Improvements
- **Index Lifecycle Management**: Implement ILM policies for automatic index management
- **Monitoring Setup**: Deploy comprehensive monitoring with alerts
- **Capacity Planning**: Review cluster sizing and scaling strategies

## Implementation Steps
1. Start with query optimization (lowest risk, high impact)
2. Schedule index maintenance during low-traffic periods
3. Monitor improvements and adjust accordingly

## Additional Resources
- [Elasticsearch Performance Tuning Guide](https://elastic.co/guide)
- [JVM Memory Management Best Practices](https://elastic.co/guide/jvm)
- [Index Lifecycle Management Documentation](https://elastic.co/guide/ilm)

*This analysis was generated by AI and should be reviewed by your team before implementation.*`

      setAnalysis(mockAnalysis)
    } catch (error) {
      console.error("Failed to analyze issue:", error)
      toast({
        title: "Error",
        description: "Failed to analyze the issue. Please try again.",
        variant: "destructive",
      })
    } finally {
      setLoading(false)
    }
  }

  const copyToClipboard = () => {
    navigator.clipboard.writeText(analysis)
    toast({
      title: "Copied!",
      description: "Analysis copied to clipboard.",
    })
  }

  const shareAnalysis = () => {
    if (navigator.share) {
      navigator.share({
        title: "Elasticsearch Issue Analysis",
        text: analysis,
      })
    } else {
      copyToClipboard()
    }
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">LLM-Powered Issue Stitcher</h1>
        <p className="text-muted-foreground">
          Describe your Elasticsearch issue and get AI-powered analysis and recommendations
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Zap className="h-5 w-5" />
            Describe Your Issue
          </CardTitle>
          <CardDescription>Provide as much detail as possible about the problem you're experiencing</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <Textarea
            placeholder="Describe your Elasticsearch issue here... Include symptoms, error messages, performance metrics, cluster configuration, and any recent changes."
            value={issueDescription}
            onChange={(e) => setIssueDescription(e.target.value)}
            rows={8}
            className="min-h-[200px]"
          />
          <Button onClick={submitIssue} disabled={loading || !issueDescription.trim()} className="w-full">
            <Send className={`mr-2 h-4 w-4 ${loading ? "animate-pulse" : ""}`} />
            {loading ? "Analyzing Issue..." : "Analyze Issue"}
          </Button>
        </CardContent>
      </Card>

      {analysis && (
        <Card>
          <CardHeader>
            <div className="flex items-center justify-between">
              <div>
                <CardTitle>AI Analysis & Recommendations</CardTitle>
                <CardDescription>Generated analysis based on your issue description</CardDescription>
              </div>
              <div className="flex space-x-2">
                <Button variant="outline" size="sm" onClick={copyToClipboard}>
                  <Copy className="mr-2 h-4 w-4" />
                  Copy
                </Button>
                <Button variant="outline" size="sm" onClick={shareAnalysis}>
                  <Share className="mr-2 h-4 w-4" />
                  Share
                </Button>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <div className="prose prose-sm max-w-none dark:prose-invert">
              <pre className="whitespace-pre-wrap text-sm leading-relaxed">{analysis}</pre>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  )
}
